#!/bin/bash

echo "🎨 Setting up Deenify notification icons"
echo "=========================================="
echo ""
echo "Step 1: Go to: https://romannurik.github.io/AndroidAssetStudio/icons-notification.html"
echo "Step 2: Upload 'assets/images/Deenifylogo.png'"
echo "Step 3: Download the generated icons"
echo ""
echo "Once you have the downloaded zip:"
echo ""
echo "1. Extract it"
echo "2. Run this command to copy the icons:"
echo ""
echo "   unzip -o ~/Downloads/notification-icons.zip -d /tmp/"
echo "   mv /tmp/res/drawable-mdpi/ic_stat_name.png android/app/src/main/res/drawable-mdpi/notification_icon.png"
echo "   mv /tmp/res/drawable-hdpi/ic_stat_name.png android/app/src/main/res/drawable-hdpi/notification_icon.png"
echo "   mv /tmp/res/drawable-xhdpi/ic_stat_name.png android/app/src/main/res/drawable-xhdpi/notification_icon.png"
echo "   mv /tmp/res/drawable-xxhdpi/ic_stat_name.png android/app/src/main/res/drawable-xxhdpi/notification_icon.png"
echo "   mv /tmp/res/drawable-xxxhdpi/ic_stat_name.png android/app/src/main/res/drawable-xxxhdpi/notification_icon.png"
echo ""
echo "3. Rebuild: npx expo run:android"
echo ""
echo "📝 Note: Replace '~/Downloads/notification-icons.zip' with your actual zip file path"

